<?php

/**
 * @file
 * This is the file that provides a quick look to show the main Drupal hooks for presenting to DAYSCRIPT
 *
 * @author Edwin Vega Moreno ('Developer Web Junior('Drupal')')
 */

/**
 * Implements hook_menu().
 */
function dayscript_menu() {

	$items = array();

	$items['example_module/form'] = array(
	    'title' => 'Formulario de pruebas Dayscript',
	    'description' => 'testing',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('dayscript_form'),
	    'access callback' => 'user_access',
	    'access arguments' => array('acces to menu Dayscript'),
	    'file' => 'includes/dayscript.forms.inc',
  	);
	$items['verified/identification'] = array(
	    'page callback' => '_retrieve_identification_validate',
	    'page arguments' => array(),
	    'type' => MENU_CALLBACK,
	    'access callback' => TRUE,
	    'file' => 'includes/dayscript.functions.inc',
  	);
  	$items['admin/config/system/quiz'] = array(
	      'title' => t('Quiz for people'),
	      'description' => t('Form for get info of people'),
	      'file' => 'includes/dayscript.forms.inc',
	      'page callback' => 'drupal_get_form',
	      'page arguments' => array('dayscript_form'),
	);
	$items['admin/config/system/quiz/settings'] = array(    
	      'title'   => t('WELCOME QUIZ'),
		  'type'    => MENU_DEFAULT_LOCAL_TASK,
	 	  'weight'  => 1,
	);

	return $items;
}

/**
 * Implements hook_permission().
 */
function dayscript_permission() {
   return array(
     'acces to menu Dayscript' =>  array(
       'title' => t('Acces to Dayscript form'),
       'description' => t('Allows access to fill out the Dayscript form'),
     ),
   );
}

/**
 * Implements hook_help().
 */
function dayscript_help($path, $arg) {
   switch ($path) {
     case 'admin/help#dayscript':
       return check_markup(file_get_contents( dirname(__FILE__) . "/README.txt") );
   }
}